### ISSUE TITLE
Glitching and now broke

### ISSUE THREAD

**Issue by ianblankg** [Taiterio/ce#39]
Some enchants have been glitching in the last update while I was on 1.9, but I had a few updated plugins that were glitching so I updated to 1.9.2 which fixed my other plugins problems but now custom enchants don't work at all. On 1.9 it was tolerable temporarily to deal with some of the ce's not working but now the plugins useless to my server. Is an update coming any time soon?

**Comment by ianblankg** [comment]
my bad, it was another plugin interfering but it's still spitting our error codes in the console and some ce's still arent working right. i keep getting the error:
19.06 23:07:54 [Server] INFO Could not pass event EntityDamageByEntityEvent to CustomEnchantments v2.4c
19.06 23:07:54 [Server] INFO org.bukkit.event.EventException
19.06 23:07:54 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
19.06 23:07:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
19.06 23:07:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:570) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:621) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:607) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.EntityEnderCrystal.damageEntity(EntityEnderCrystal.java:87) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.EntityArrow.a(EntityArrow.java:268) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.EntityArrow.m(EntityArrow.java:188) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTippedArrow.m(EntityTippedArrow.java:68) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-f04e043-52c7fc0]
19.06 23:07:54 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
19.06 23:07:54 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R1.entity.CraftEnderCrystal cannot be cast to org.bukkit.entity.LivingEntity
19.06 23:07:54 [Server] INFO at com.taiter.ce.Enchantments.Global.IceAspect.effect(IceAspect.java:73) ~[?:?]
19.06 23:07:54 [Server] INFO at com.taiter.ce.CEventHandler.handleBows(CEventHandler.java:244) ~[?:?]
19.06 23:07:54 [Server] INFO at com.taiter.ce.CEListener.EntityDamageByEntityEvent(CEListener.java:427) ~[?:?]

**Comment by Taiterio** [comment]
Thanks for the report!

The above error seems to occur when you shoot Non-Living entities (in your case, an EnderCrystal). This will be fixed in the next update

**Comment by ghost** [comment]
I will work on it when I get home
